fix(plugin-csl): defer error to citeproc-js
Defer error for when @bibliography/entry does not exist to citeproc-js, 
which gives a nice, clear error, as opposed to

    TypeError: Cannot read property 'Symbol(proxied)' of undefined

See a372012